import type { Product, Category, Order, Customer } from '../types'

export const INITIAL_CATEGORIES: Category[] = [
  { id: '1', name: 'Fashion', slug: 'fashion', description: 'Clothing and accessories', image: '/category-fashion.svg' },
  { id: '2', name: 'Electronics', slug: 'electronics', description: 'Gadgets and devices', image: '/category-electronics.svg' },
  { id: '3', name: 'Home & Kitchen', slug: 'home-kitchen', description: 'Home essentials', image: '/category-home.svg' },
  { id: '4', name: 'Beauty', slug: 'beauty', description: 'Personal care & cosmetics', image: '/category-beauty.svg' },
  { id: '5', name: 'Sports', slug: 'sports', description: 'Fitness and outdoor gear', image: '/category-sports.svg' },
]

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Cotton Shirt',
    slug: 'premium-cotton-shirt',
    description: '100% premium cotton, comfortable and breathable, perfect for daily wear.',
    category: 'Fashion',
    price: 1250,
    discount: 15,
    stock: 42,
    sku: 'SHIRT-001',
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80'],
    rating: 4.5,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Smart Watch Pro',
    slug: 'smart-watch-pro',
    description: 'Advanced health tracking, waterproof design, long battery life.',
    category: 'Electronics',
    price: 3200,
    discount: 20,
    stock: 15,
    sku: 'WATCH-001',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80'],
    rating: 4.8,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Ceramic Coffee Maker',
    slug: 'ceramic-coffee-maker',
    description: 'Elegant ceramic design, 5-cup capacity, perfect brewing temperature.',
    category: 'Home & Kitchen',
    price: 2800,
    discount: 0,
    stock: 30,
    sku: 'COFFEE-001',
    images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=600&q=80'],
    rating: 4.3,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    name: 'Running Shoes Pro',
    slug: 'running-shoes-pro',
    description: 'Lightweight running shoes with superior cushioning and grip.',
    category: 'Sports',
    price: 2500,
    discount: 10,
    stock: 25,
    sku: 'SHOE-001',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80'],
    rating: 4.7,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-28',
  },
  {
    id: '5',
    name: 'Leather Wallet',
    slug: 'leather-wallet',
    description: 'Genuine leather, card slots, coin pocket, durable construction.',
    category: 'Fashion',
    price: 850,
    discount: 0,
    stock: 55,
    sku: 'WALLET-001',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80'],
    rating: 4.2,
    isFeatured: false,
    isActive: true,
    createdAt: '2024-04-01',
  },
  {
    id: '6',
    name: 'Wireless Headphones',
    slug: 'wireless-headphones',
    description: 'Noise cancelling, 30hr battery, premium sound quality.',
    category: 'Electronics',
    price: 4500,
    discount: 25,
    stock: 8,
    sku: 'HEADPHONE-001',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80'],
    rating: 4.6,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-02-10',
  },
  {
    id: '7',
    name: 'Digital Camera 4K',
    slug: 'digital-camera-4k',
    description: '20MP sensor, 4K video recording, built-in stabilization.',
    category: 'Electronics',
    price: 25000,
    discount: 10,
    stock: 4,
    sku: 'CAMERA-001',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80'],
    rating: 4.9,
    isFeatured: false,
    isActive: true,
    createdAt: '2024-01-05',
  },
  {
    id: '8',
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    description: 'Non-slip, eco-friendly TPE material, extra thick for comfort.',
    category: 'Sports',
    price: 1200,
    discount: 0,
    stock: 35,
    sku: 'MAT-001',
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&q=80'],
    rating: 4.4,
    isFeatured: false,
    isActive: true,
    createdAt: '2024-03-15',
  },
]

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    customerName: 'Ayesha Khan',
    customerEmail: 'ayesha.khan@email.com',
    customerPhone: '+880 1712 345678',
    address: 'House 42, Road 11, Banani',
    city: 'Dhaka',
    postalCode: '1213',
    items: [
      {
        productId: '1',
        productName: 'Premium Cotton Shirt',
        productImage: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
        price: 1062.5,
        quantity: 1,
      },
    ],
    total: 1112.5,
    discount: 187.5,
    subtotal: 1250,
    deliveryCharge: 50,
    paymentMethod: 'cash-on-delivery',
    paymentStatus: 'paid',
    status: 'delivered',
    orderDate: '2024-05-10',
    createdAt: '2024-05-10T10:30:00Z',
    updatedAt: '2024-05-10T10:30:00Z',
  },
  {
    id: 'ORD-002',
    customerName: 'Rahman Islam',
    customerEmail: 'rahman.islam@email.com',
    customerPhone: '+880 1819 876543',
    address: 'GEC Circle, Nasirabad',
    city: 'Chittagong',
    postalCode: '4000',
    items: [
      {
        productId: '2',
        productName: 'Smart Watch Pro',
        productImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
        price: 2560,
        quantity: 1,
      },
    ],
    total: 2610,
    discount: 640,
    subtotal: 2560,
    deliveryCharge: 50,
    paymentMethod: 'online',
    paymentStatus: 'paid',
    status: 'processing',
    orderDate: '2024-05-12',
    createdAt: '2024-05-12T14:15:00Z',
    updatedAt: '2024-05-12T14:15:00Z',
  },
]

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: '1',
    name: 'Ayesha Khan',
    email: 'ayesha.khan@email.com',
    phone: '+880 1712 345678',
    address: 'House 42, Road 11, Banani',
    city: 'Dhaka',
    postalCode: '1213',
    isActive: true,
    totalOrders: 12,
    totalSpent: 25000,
    orderHistory: [
      { orderId: 'ORD-001', total: 1112.5, date: '2024-05-10', status: 'delivered' },
    ],
  },
  {
    id: '2',
    name: 'Rahman Islam',
    email: 'rahman.islam@email.com',
    phone: '+880 1819 876543',
    address: 'GEC Circle, Nasirabad',
    city: 'Chittagong',
    postalCode: '4000',
    isActive: true,
    totalOrders: 8,
    totalSpent: 18500,
    orderHistory: [
      { orderId: 'ORD-002', total: 2610, date: '2024-05-12', status: 'processing' },
    ],
  },
]
